apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: perses-operator
    app.kubernetes.io/instance: metrics-reader-binding
    app.kubernetes.io/name: perses-operator
    app.kubernetes.io/part-of: perses-operator
    app.kubernetes.io/version: 0.5.0
  name: perses-operator-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: perses-operator-metrics-reader
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
