apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/created-by: perses-operator
    app.kubernetes.io/name: perses-operator
    app.kubernetes.io/part-of: perses-operator
    app.kubernetes.io/version: 0.5.0
  name: perses-operator
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/created-by: perses-operator
    app.kubernetes.io/name: perses-operator
    app.kubernetes.io/part-of: perses-operator
